### ISSUE TITLE
A some review

### ISSUE THREAD

**Issue by volyx** [skqwk/database#1]
a) При запуске

```dart
$ dart main.dart 
Unhandled exception:
NoSuchMethodError: The method 'add' was called on null.
Receiver: null
Tried calling: add(Instance of 'Row')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      SemyonDB.addRow (file:///Users/volyx/Projects/database/main.dart:27:23)
#2      main (file:///Users/volyx/Projects/database/main.dart:105:6)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
b) https://github.com/skqwk/database/blob/f89b8b76d56d071e96a66a38e9c25aa418bd7443/main.dart#L20-L22

Функиция не удаляет коллекцию из списка

c) https://github.com/skqwk/database/blob/f89b8b76d56d071e96a66a38e9c25aa418bd7443/main.dart#L51-L59

Хорошая практика всегда явно писать return, чтобы читателю кода было понятно, что возвращает функция без погружения в синтаксис dart

https://github.com/skqwk/database/blob/f89b8b76d56d071e96a66a38e9c25aa418bd7443/main.dart#L42-L49
Здесь тоже return
В остальных функциях тоже

d) https://github.com/skqwk/database/blob/f89b8b76d56d071e96a66a38e9c25aa418bd7443/main.dart#L51
Каждый раз при вызове `findCollection` мы проходимся по списку, и ищем коллекцию по имени. Может быть есть структура данных, которая позволит делать это быстрее?

https://github.com/skqwk/database/blob/f89b8b76d56d071e96a66a38e9c25aa418bd7443/main.dart#L75

e) Cage - клетка? :)
Давай наверное переименуем в Field, а Collection в Table, чтобы было более похоже на другие базы данных

**Comment by skqwk** [comment]
исправил a, b, c, d, e в новом коммите
